import { 
  Loader2, 
  User, 
  FileText, 
  Menu, 
  Home, 
  LogOut, 
  RefreshCw, 
  History,
  ChevronDown,
  Copy,
  Download,
  ExternalLink,
  Clock,
  BarChart3,
  Upload,
  FileAudio,
  Link2
} from "lucide-react";

export const Icons = {
  spinner: Loader2,
  upload: Upload,
  fileAudio: FileAudio,
  link: Link2,
  user: User,
  fileText: FileText,
  menu: Menu,
  home: Home,
  logout: LogOut,
  refresh: RefreshCw,
  history: History,
  chevronDown: ChevronDown,
  copy: Copy,
  download: Download,
  externalLink: ExternalLink,
  clock: Clock,
  barChart: BarChart3,
};